*  Configurator
/Configurator/ is a tool for quickly modifying values of all parts of
/Arma 3/. The tool is comprised of two components, a Google Spreadsheet
and a Google AppsScript Macro. The spreadsheet acts as a
human-readable representation of many of the items and settings
available in /Arma 3/ that can be edited as a normal spreadsheet. The
AppsScript component then takes all of the definitions in the
spreadsheet, and converts them into the =config.cpp= format that Arma
expects. 

** Dependencies
As it stands currently, /Configurator/ depends on both =Community Base
Addons= and =SMA Weapons.= This may change in the future. 

** Usage
*** Edit the Spreadsheet
Open up the spreadsheet and start editing the values to your preference. Make
sure to check the */Notes/* section for the constraints associated with each sheet. 

***  Save the output
When you feel that the =config= is to your liking, open up the /Script Editor/ by
going to =Tools > Script Editor=. From here, run the AppScript component by
pressing the play button on the toolbar. 


When the script is done running, go back to the spreadsheet and open up the the
=Output= sub-sheet. Assuming nothing went wrong, column =A= should now contain the
resulting =config.cpp=.


Select the whole column and copy it to your clipboard. Paste the config into a
text file called =config.cpp= and save it, preferably into its own folder.

*** Compile the Addon
Now that we have the config ready to go, open /Arma 3 Tools/ and go to the
/Binarize/ tool, you can use /armake2/ or /pboproject/ if you prefer. Set the addon
source directory to wherever you have the =config.cpp= saved and the output
directory to =/{Arma 3 Root}/@Configurator/addons=. 

Start the /Arma 3/ launcher and enable =Configurator= in your mods list.

** Notes
*** Vehicle Weapons
   Vehicle Weapons with multiple ammo modes requires
   classname to be non empty to be able to key off of
   when parsing.
   
** Todo
 - [X] Basic Settings
 - [X] Ammo
 - [X] Infantry Weapons
 - [X] Infantry Optics
 - [X] Infantry Armor
 - [X] Infantry Types
 - [X] Vehicle Weapons
 - [ ] Vehicle Armor

