import { Parsers } from "../infantryOptics";

test("Infantry Optics", () => {
  const data: string[][] = [
    [
      "optic_Arco",
      "ItemCore",
      "ARCO",
      "ARCO",
      "",
      "1-2x Combat Optic",
      "8",
      "0.1",
      "ARCO2collimator",
      "",
      "ADS (1.5x)",
      "0.5",
      "0.5",
      "0.5",
      "",
      "ARCO2scope",
      "ARCO2collimator",
      "2x",
      "0.25",
      "0.25",
      "0.25",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      ""
    ],
    ["SMA", "SMA", "SMA", "SMA", ""],
    [
      "SMA_ELCAN_SPECTER",
      "ItemCore",
      "ELCAN SpecterDR DFOV14-C1",
      "SpecterDR",
      "4x Combat Optic",
      "1-4x Combat Optic",
      "10",
      "",
      "ACOG4x",
      "",
      "2-4x",
      "0.125",
      "0.25",
      "0.25",
      "",
      "IronSight",
      "",
      "ADS (1.5x)",
      "0.5",
      "0.5",
      "0.5",
      "",
      "RedDotSight",
      "IronSight",
      "ADS (1.5x)",
      "0.5",
      "0.5",
      "0.5",
      ""
    ]
  ];
  expect(Parsers.parseInfantryOptics(data)).toEqual([
    "Class optic_Arco: ItemCore {",
    "displayTitle='ARCO';",
    "descriptionShort='1-2x Combat Optic';",
    "Class ItemInfo: InventoryOpticsItem_Base_F {",
    "mass=8;",
    "inertia=0.1;",
    "Class OpticsModes {",
    "Class ARCO2collimator {",
    "minFOV=0.5",
    "initFOV=0.5",
    "maxFOV=0.5",
    "};",
    "Class ARCO2scope : ARCO2collimator {",
    "minFOV=0.25",
    "initFOV=0.25",
    "maxFOV=0.25",
    "};",
    "};",
    "};",
    "};",
    "Class SMA_ELCAN_SPECTER: ItemCore {",
    "displayTitle='SpecterDR';",
    "descriptionShort='1-4x Combat Optic';",
    "Class ItemInfo: InventoryOpticsItem_Base_F {",
    "mass=10;",
    "Class OpticsModes {",
    "Class ACOG4x {",
    "minFOV=0.125",
    "initFOV=0.25",
    "maxFOV=0.25",
    "};",
    "Class IronSight {",
    "minFOV=0.5",
    "initFOV=0.5",
    "maxFOV=0.5",
    "};",
    "Class RedDotSight : IronSight {",
    "minFOV=0.5",
    "initFOV=0.5",
    "maxFOV=0.5",
    "};",
    "};",
    "};",
    "};"
  ]);
});
