import {Parsers} from '../vehicleWeapons'

test("Vehicle Weapons", () => {
  const data: string[][] = [
    [
      "GMG_40mm",
      "GMG_F",
      "",
      "",
      "",
      "",
      "20.0",
      "",
      "",
      "",
      "manual: GMG_F",
      "",
      "0.005",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      ""
    ],
    [
      "autocannon_40mm_CTWS",
      "autocannon_Base_F",
      "HE: autocannon_Base_F",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "player: player",
      "",
      "0.00150",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      ""
    ],
    [
      "autocannon_40mm_CTWS",
      "autocannon_Base_F",
      "AP: autocannon_Base_F",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "player: player",
      "",
      "0.00090",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      ""
    ]
  ];

  expect(Parsers.parseVehicleWeapons(data)).toEqual([
    "class GMG_40mm : GMG_F {",
    "magazineReloadTime=20.0;",
    "class manual: GMG_F {",
    "dispersion=0.005;",
    "};",
    "};",
    "class autocannon_40mm_CTWS : autocannon_Base_F {",
    "class HE: autocannon_Base_F {",
    "class player: player {",
    "dispersion=0.00150;",
    "};",
    "};",
    "class AP: autocannon_Base_F {",
    "class player: player {",
    "dispersion=0.00090;",
    "};",
    "};",
    "};"
  ]);
});
